### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by ewallah** [fmido88/moodle-enrol_wallet#11]
The boolean $primary is deprecated and replaced by $type, use single_button::BUTTON_PRIMARY or self::BUTTON_SECONDARY instead
line 907 of /lib/outputcomponents.php: call to debugging()
line 120 of /enrol/wallet/extra/topup.php: call to single_button->__construct()

Moodle 4.2.3+
Php: 8.1.26

**Comment by fmido88** [comment]
Thanks @ewallah for the feedback, I'll fix this in the next release.

**Comment by fmido88** [comment]
Fixed

**Comment by ewallah** [comment]
THX
