### ISSUE TITLE
Idea: Allow precise discount values in Offers

### ISSUE THREAD

**Issue by Buda9** [fmido88/moodle-enrol_wallet#21]
In Offers, in percentage amount of discount feature, when I try to enter a discount with decimals or dots, like 32,50% or 32.50%, it rounds it to the nearest whole number, turning it into either 32% or 33%. This prevents me from entering precise discount values. What do you think about not rounding it up?

![Screenshot_227](https://github.com/fmido88/moodle-enrol_wallet/assets/1422662/5e095c1f-4996-4ce1-97d7-17c3eac62764)

Edit: Here is real life scenario with my discounts that I plan to use:

![Screenshot_228](https://github.com/fmido88/moodle-enrol_wallet/assets/1422662/81d6c730-2a85-4097-9e3f-60c248939451)

**Comment by fmido88** [comment]
Hi @Buda9 
This has been fixed

**Comment by Buda9** [comment]
works great, thank you
