### ISSUE TITLE
Idea: When inside category, automatically select that category for Offers (wallet block)

### ISSUE THREAD

**Issue by Buda9** [fmido88/moodle-enrol_wallet#22]
When we use Wallet block and we have Offers, students must select category they want to use to top up. What do you think that category is automatically "recognized" and selected?

1. This is what students see inside a category:

![Screenshot_226](https://github.com/fmido88/moodle-enrol_wallet/assets/1422662/657378ce-7afa-4a9d-97ad-76b937291409)

2. And this is how it looks when they select category:

![Screenshot_225](https://github.com/fmido88/moodle-enrol_wallet/assets/1422662/abcfd03a-eebf-4762-a323-2110dbcb93e1)

I'm afraid not many people will "know" they should select category first, and they'll go ahead and top up without selecting category. But I might be wrong. What do you think about tihs?

**Comment by fmido88** [comment]
Hi @Buda9
I'm not convinced to do it as the default always should be site balance not category balance.
we can add a notification message that there is offers in categories and the user could browse this offers before topping up.

**Comment by Buda9** [comment]
Well yes, that make perfect sense regarding site balance as default option. Notification would be nice UX detail

**Comment by fmido88** [comment]
@Buda9
I'll work on it soon

**Comment by fmido88** [comment]
Hello @Buda9
In the  last commit I added a default selection to category according the page context, I the block placed in a category or a course, the default selection should be this category if existed in the options.

**Comment by Buda9** [comment]
@fmido88 this looks so great. I inspected the code and it's perfect. Thank you very much 🤗
