### ISSUE TITLE
Idea: Make Offers responsive

### ISSUE THREAD

**Issue by Buda9** [fmido88/moodle-enrol_wallet#23]
Me again :) I'm sure that you probably plan to do this. Anyway, it would be awesome to make Offers "table" preview responsive, by making it in one row per one offer on smaller screen size

![Screenshot_231](https://github.com/fmido88/moodle-enrol_wallet/assets/1422662/7fac2f63-3df2-4d3c-93d2-14c7d2eefef3)

PS. This one too

![Screenshot_230](https://github.com/fmido88/moodle-enrol_wallet/assets/1422662/7e0e5d7c-272e-4d0f-b7f8-d38fe760475d)

**Comment by fmido88** [comment]
Hello @Buda9 
I really did my best in the latest update. You can check it now.

**Comment by Buda9** [comment]
Great! I'll test it soon, plus all other stuff that you recently worked on and get back to you

**Comment by Buda9** [comment]
It looks really awesome now. Thank you very much for your effort
