### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by chyntori** [fmido88/moodle-enrol_wallet#28]
Whenever transaction happened, error show.
It may be due to my openlitespeed server, mariadb or php setting. Please help solve this error.
Below is some screenshot.
I am trying to add some credits to a user
1
![Screenshot from 2024-06-01 16-14-53](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/21acd8ec-b974-4ca9-953a-cf690ef9c344)
2
![Screenshot from 2024-06-01 16-15-03](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/837c6b4b-bf3e-4b24-ab83-4ad7f335f956)
3 This error showed.
![Screenshot from 2024-06-01 16-15-11](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/047f4b82-3f16-4f7f-98b1-6e3db8101712)
4 clicking more information leads to this page.
![Screenshot from 2024-06-01 16-15-34](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/d85c77e9-b305-400c-bc38-968224b01db6)
5 Here i am trying to purchase the course
![Screenshot from 2024-06-01 16-19-59](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/db067cd7-16ec-4a11-9e83-903ef12cfd89)
6
![Screenshot from 2024-06-01 16-20-21](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/d0f3c1ac-61eb-4396-b37e-c7c17c22a226)
7 
![Screenshot from 2024-06-01 16-20-33](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/a2e3d4c9-a761-443e-9dcc-856f0afc19c1)
8 clicking continue lead here.
![Screenshot from 2024-06-01 16-20-43](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/33fc3b4f-905e-4c44-a010-d1999ab975fd)

when adding credits. It shows error but credits got added nonetheless.
but when purchasing, credits got deducted but course is not purchased.

**Comment by chyntori** [comment]
regarding the help page at page 4, I have change the max_allowed_packet and max_binlog_cache_size to 1G and 4G respectively at /etc/mysql/mariadb.conf.d/50-server.cnf on my ubuntu 24.04 vps on hostinger.

**Comment by Buda9** [comment]
Hey @chyntori, regarding first screenshot, value can't be that large. Try without last zero

**Comment by fmido88** [comment]
Thank you @chyntori for reporting this
The error corresponding to database error related to the number of digits in the numbers

In the next update I'll modify the DB tables structure to allow the fields of costs and balances to sustain more digits.

For the second error about missing parameter that happen because of the first error then redirect again to the confirmation page but without the parameters, if the first error fixed, the second will be fixed too.

I'll upload the new fixed version soon.

**Comment by chyntori** [comment]
Dear Sir, I have no more error about "error writing to database" again after update.
But I still can't purchase a course. This time when I tried to purchase a course the picture 8 showed up immediately, saying a required parameter (id) was missing.
