### ISSUE TITLE
Dear Sir, I have no more error about "error writing to database" again after update.

### ISSUE THREAD

**Issue by chyntori** [fmido88/moodle-enrol_wallet#30]
Dear Sir, I have no more error about "error writing to database" again after update.
But I still can't purchase a course. This time when I tried to purchase a course the picture 8 showed up immediately, saying a required parameter (id) was missing.

_Originally posted by @chyntori in https://github.com/fmido88/moodle-enrol_wallet/issues/28#issuecomment-2177892401_

It may be because of my moodle settings, but what should i change?

**Comment by fmido88** [comment]
Hello @chyntori
Could you provide me a screenshot of the error
The original one the paramere was (instance) now its (id) and the code is slightly different than before

**Comment by chyntori** [comment]
1
![image](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/ce51f559-328e-4289-82d6-7888eb1c404d)
2
![image](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/499c0cb1-cc94-4901-8390-cb50b3e04b8c)
3
![image](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/33213b47-0774-42ae-ac5c-a4bd5d215e0d)
4 after i click continue it change into this
![image](https://github.com/fmido88/moodle-enrol_wallet/assets/143638799/7c541e1c-4e8b-4605-9ebe-5bc0ef462992)
anymore clicking continue, it will show screenshot 4

**Comment by chyntori** [comment]
If it is needed, i will change my hosting to vps hosting again and start from scratch. Just guide me which settings i should change.

**Comment by fmido88** [comment]
@chyntori I spotted the probelm within my code
Try the latest version now

**Comment by chyntori** [comment]
Thanks, I have tested and it's okay now.
Thanks a lot to you.
You are a great help for guys like me in 3rd world countries who can't use other payment methods and ur plugin really solve it.

**Comment by chyntori** [comment]
Is there anything I could do to help your plugin success?

**Comment by fmido88** [comment]
You are welcome @chyntori
I'm from Egypt which considered a 3rd world country too 😅
And thank you for your offer
