### ISSUE TITLE
Improvement: Send pdf invoice to user via email

### ISSUE THREAD

**Issue by Buda9** [fmido88/moodle-enrol_wallet#32]
It would be awesome if we could have this. Please allow me to try first to build this feature.

**Comment by fmido88** [comment]
I think that the pdf invoice should be sent from the payment gateway plugin which used to charging the wallet not the enrolment plugin.

**Comment by Buda9** [comment]
Here it is: https://github.com/Buda9/moodle-local_invoicepdf 🎉

I'm still testing all functionalities, so it's not advised to use it on production site

**Comment by fmido88** [comment]
@Buda9 great work, I'll take a look on it.
