### ISSUE TITLE
Showing error Exception - Class 'core_payment\helper' not found

### ISSUE THREAD

**Issue by development-csipl** [fmido88/moodle-enrol_wallet#4]
We have added moodle-enrol_wallet plugin, however after adding the plugin. Website is showing below error.

Exception - Class 'core_payment\helper' not found.
![core_payment](https://github.com/fmido88/moodle-enrol_wallet/assets/59190319/dccd9c50-9913-4b28-8e8e-c0666a708ace)

Any suggestion would be helpful.

Thanks in advance.

**Comment by fmido88** [comment]
Greetings, Yes indeed this happen for moodle versions less than 3.11 as there is no payment helper class yet, What version of moodle do you use?

**Comment by fmido88** [comment]
To resolve this for now you can first delete settings.php file, then uninstall the plugin.
For me in further updates I'll try to make the plugin compatible with lower versions of moodle

**Comment by development-csipl** [comment]
Thanks. We are using Moodle version 3.9.7. We have tried to download "Payment" folder from Moodle version 3.11 and uploaded on our version, however that did not work.

Any suggestion would be helpful.

Thanks

**Comment by fmido88** [comment]
I think it is safer to update moodle version

**Comment by fmido88** [comment]
Greetings @development-csipl
In the latest version of this plugin, I add a check for the existance of payment classes before any action regarding it.
You can try it now and feel free to report any new issue.

**Comment by development-csipl** [comment]
How can we downgrade the plugin for Moodle 3.9.

**Comment by development-csipl** [comment]
> Greetings @development-csipl In the latest version of this plugin, I add a check for the existance of payment classes before any action regarding it. You can try it now and feel free to report any new issue.

We are facing same issue. Also getting below issue initially.

Install plugin from ZIP file
Validating enrol_wallet ... Error
  [Error] Required Moodle version [2020110911] 
Installation aborted due to validation failure

**Comment by fmido88** [comment]
@development-csipl that is because the dependants on version.php file if you can change it before installing to 2016120509, and I'll change it in the new version and complete the tests

**Comment by fmido88** [comment]
I decreased the required version, now it should be installed into moodle 3.9, I tested it using moodle-ci, but not fully tested.
You can try now and tell me if there is anything goes wrong.
