### ISSUE TITLE
please don't call curl_init() directly

### ISSUE THREAD

**Issue by danmarsden** [fmido88/moodle-enrol_wallet#7]
https://github.com/fmido88/moodle-enrol_wallet/blob/main/classes/wordpress.php#L54

Please don't initiate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions and takes care of various security and proxy settings in moodle.

This isn't documented well, but do a search on core code for curl to see it's use.

**Comment by fmido88** [comment]
I thought it is tough but it turned to be quit easy. I changed the code.
